# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/97fab64e-bfa7-4d0b-a9ab-b1eeb0fa26f2";
      fsType = "btrfs";
      options = [ "subvol=nixos" ];
    };

  boot.initrd.luks.devices."nixos-enc".device = "/dev/disk/by-uuid/cbb9a4d9-b7c8-442f-baf9-b79b7610f5be";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F474-F912";
    fsType = "vfat";
  };

  swapDevices = [ ];

  # Video Drivers
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.opengl.enable = true;
  hardware.opengl.extraPackages = [ pkgs.linuxPackages.nvidia_x11.out ];

  # These settings work, but external displays do not
  # services.xserver = {
  #   videoDrivers = [ "intel" ];
  #   deviceSection = ''BusID "PCI:0:2:0"'';
  # };
  # hardware.bumblebee = {
  #   enable = true;
  #   connectDisplay = true;
  # };

  # nixpkgs.config.packageOverrides = pkgs: rec {
  #   bumblebee = pkgs.bumblebee.override {
  #     extraNvidiaDeviceOptions = ''
  #       Option "ProbeAllGpus" "false"
  #       Option "AllowEmptyInitialConfiguration"
  #     EndSection

  #     Section "Screen"
  #       Identifier "Default Screen"
  #       Device "DiscreteNvidia"
  #     '';
  #   };
  # };

  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.pulseaudio = {
    enable = true;
    package = pkgs.pulseaudioFull;
    extraConfig = "
                  load-module module-alsa-sink device=hdmi:0
                  load-module module-bluetooth-discover
                  load-module module-bluetooth-policy
                  load-module module-combine-sink sink_name=combined
                  load-module module-zeroconf-discover
                  load-module module-zeroconf-publish
                  load-module module-raop-discover
                  ";
    tcp = {
      enable = true;
      anonymousClients.allowedIpRanges = ["127.0.0.1"];
    };
  };
  hardware.bluetooth = {
    enable = true;
    extraConfig = "
      [General]
      Enable=Source,Sink,Media,Socket
    ";
  };
}
