# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/97fab64e-bfa7-4d0b-a9ab-b1eeb0fa26f2";
      fsType = "btrfs";
      options = [ "subvol=nixos" ];
    };

  boot.initrd.luks.devices."nixos-enc".device = "/dev/disk/by-uuid/cbb9a4d9-b7c8-442f-baf9-b79b7610f5be";

  fileSystems."/home/jasonmj/org" =
    { device = "https://nextcloud.forthelonghaul.net/remote.php/webdav/";
      fsType = "davfs";
      options = [
        "noauto"
        "uid=1000"
        "gid=100"
        "x-systemd.automount"
      ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F474-F912";
      fsType = "vfat";
    };

  fileSystems."/mnt/storage" =
    { device = "/dev/disk/by-uuid/a1404c51-c21d-4e1a-9438-1c534f4610f5";
      fsType = "ext4";
      options = ["noauto" "x-systemd.automount"];
    };

  fileSystems."/mnt/backup" =
    { device = "/dev/disk/by-uuid/c88fff93-1ad8-4f91-99c4-1b4ce2461370";
      fsType = "ext4";
      options = ["noauto" "x-systemd.automount"];
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  # Video Drivers
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.opengl.enable = true;

  # Bluetooth
  nix.maxJobs = lib.mkDefault 12;
  hardware.bluetooth = {
    enable = true;
    settings = {
      General = {
        Enable = "Source,Sink,Media,Socket";
      };
    };
    package = pkgs.bluezFull;
  };
  hardware.pulseaudio = {
    enable = true;
    package = pkgs.pulseaudioFull;
    extraConfig = "
                  load-module module-alsa-sink device=hdmi:0
                  load-module module-bluetooth-discover
                  load-module module-bluetooth-policy
                  load-module module-bluez5-discover
                  load-module module-combine-sink sink_name=combined
                  load-module module-zeroconf-discover
                  load-module module-zeroconf-publish
                  load-module module-raop-discover
                  ";
    tcp = {
      enable = true;
      anonymousClients.allowedIpRanges = ["127.0.0.1"];
    };
  };

  # Trackpoint
  hardware.trackpoint = {
    enable = true;
    emulateWheel = false;
    sensitivity = 140;
    speed = 115;
  };
}
